// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmBAtI5Pt_1iRUQcGL1l7THx1FGwauFH0',
    appId: '1:966810486701:web:1e46c54b1b51a2363fc324',
    messagingSenderId: '966810486701',
    projectId: 'loginpractice-cbe21',
    authDomain: 'loginpractice-cbe21.firebaseapp.com',
    storageBucket: 'loginpractice-cbe21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4EzbhZi6egpx9ZHqXBKOlh2lmDXade-c',
    appId: '1:966810486701:android:7bd17ca953cf42fc3fc324',
    messagingSenderId: '966810486701',
    projectId: 'loginpractice-cbe21',
    storageBucket: 'loginpractice-cbe21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAaB79Y3NeKmqmjhWRZoWHOcNGdbyhvKg',
    appId: '1:966810486701:ios:7d52a89161a61cc33fc324',
    messagingSenderId: '966810486701',
    projectId: 'loginpractice-cbe21',
    storageBucket: 'loginpractice-cbe21.appspot.com',
    androidClientId: '966810486701-phlqd4htmej2dosa93h42tk0ekquksja.apps.googleusercontent.com',
    iosClientId: '966810486701-l7h6k1uqpav5v514874nc322gikfu3u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSocialMedialTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAaB79Y3NeKmqmjhWRZoWHOcNGdbyhvKg',
    appId: '1:966810486701:ios:7d52a89161a61cc33fc324',
    messagingSenderId: '966810486701',
    projectId: 'loginpractice-cbe21',
    storageBucket: 'loginpractice-cbe21.appspot.com',
    androidClientId: '966810486701-phlqd4htmej2dosa93h42tk0ekquksja.apps.googleusercontent.com',
    iosClientId: '966810486701-l7h6k1uqpav5v514874nc322gikfu3u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSocialMedialTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmBAtI5Pt_1iRUQcGL1l7THx1FGwauFH0',
    appId: '1:966810486701:web:af9d3d7bdfb8ab083fc324',
    messagingSenderId: '966810486701',
    projectId: 'loginpractice-cbe21',
    authDomain: 'loginpractice-cbe21.firebaseapp.com',
    storageBucket: 'loginpractice-cbe21.appspot.com',
  );
}
